#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=install_env
#SBATCH --time=01:00:00
#SBATCH --output=./slurm_out/install_env.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

cd ~/ai4mi_project_group8

# Properly initialize conda from the module path
source $EBROOTMINICONDA3/etc/profile.d/conda.sh

# Create a clean environment
conda create -n ai4mi python=3.11 -y
conda activate ai4mi

# Install project-specific requirements
pip install --upgrade pip
pip install -r requirements.txt

echo "Environment set up"