#!/bin/bash
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=make_data
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:30:00
#SBATCH --output=out/slice_%A.out

module load 2023
module load Anaconda3/2023.07-2
source activate ai4mi_env

cd /home/scur1049/ai4mi_project_group8

# unzip segthor
make data/segthor_train

# fix heart
make data/segthor_fixed

# slice data into png
make data/SEGTHOR_CLEAN CFLAGS=-O