_wandb:
    value:
        cli_version: 0.22.1
        e:
            vqeg6oi5805brhpimjbzkjfshz3o9qqe:
                args:
                    - --dataset
                    - SEGTHOR_CLEAN_AUG
                    - --mode
                    - full
                    - --epochs
                    - "25"
                    - --dest
                    - results/segthor_aug
                    - --gpu
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 72
                cpu_count_logical: 72
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "270185529344"
                        used: "6421475328"
                email: guerenaalex@gmail.com
                executable: /home/scur1051/.conda/envs/ai4mi/bin/python
                git:
                    commit: 9fcf06229e20c1f59123065e9d6c9541f2909366
                    remote: git@github.com:IwkooO/ai4mi_project_group8.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-92a70bd8-8a20-a0f2-b30f-9e3ddf465ccc
                host: gcn11.local.snellius.surf.nl
                memory:
                    total: "540635033600"
                os: Linux-5.14.0-427.88.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /gpfs/home5/scur1051/ai4mi_project_group8/main.py
                python: CPython 3.11.13
                root: /gpfs/home5/scur1051/ai4mi_project_group8
                slurm:
                    cluster_name: snellius
                    conf: /var/spool/slurm/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "18"
                    eclibr: "0"
                    ecplug: "1"
                    erlast: sbatch
                    ersbac: "1"
                    export_env: ALL
                    get_user_env: "1"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: gpuuva061
                    job_cpus_per_node: "18"
                    job_end_time: "1759628080"
                    job_gid: "62845"
                    job_gpus: "0"
                    job_id: "15106277"
                    job_name: train_model
                    job_nodelist: gcn11
                    job_num_nodes: "1"
                    job_partition: gpu_a100
                    job_qos: normal
                    job_start_time: "1759619079"
                    job_uid: "63311"
                    job_user: scur1051
                    jobid: "15106277"
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gcn11
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    step_gres: gres/cpu:0
                    submit_dir: /gpfs/home5/scur1051/ai4mi_project_group8
                    submit_host: int6.local.snellius.surf.nl
                    task_pid: "1680130"
                    tasks_per_node: "18"
                    topology_addr: root.ibsw6.gcn11
                    topology_addr_pattern: switch.switch.node
                startedAt: "2025-10-04T23:04:56.259555Z"
                writerId: vqeg6oi5805brhpimjbzkjfshz3o9qqe
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 16
            "4": 3.11.13
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
batch_size:
    value: 8
dataset:
    value: SEGTHOR_CLEAN_AUG
epochs:
    value: 25
learning_rate:
    value: 0.0005
mode:
    value: full
