#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=augment_data
#SBATCH --time=02:30:00
#SBATCH --output=./slurm_out/augment_data.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

cd ~/ai4mi_project_group8

source activate ai4mi

pip install opencv-python

python data_augmentation.py \
  --augmentations flip,rotate,noise \
  --input_dir data/SEGTHOR_CLEAN \
  --output_dir data/$DATA_NAME
