#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=augment_data_alb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=8GB
#SBATCH --time=02:00:00
#SBATCH --output=out/augment_data_alb.log

#exit if an error occurs
set -e

module load 2023
module load Anaconda3/2023.07-2

cd $HOME/ai4mi_project_group8/
source $(conda info --base)/etc/profile.d/conda.sh
source activate ai4mi_env

cd $HOME/ai4mi_project_group8/

source activate ai4mi_env

pip install opencv-python
pip install albumentations[imgaug] albumentations[opencv] 

python data_augmentation_alb.py \
  --input_dir data/SEGTHOR_CLEAN \
  --output_dir data/SEGTHOR_CLEAN_AUG_ALB \
  --augmentations hflip,rotate,elastic,brightness_contrast,gauss_noise,blur

cp data/SEGTHOR_CLEAN/spacing.pkl data/SEGTHOR_CLEAN_AUG_ALB/spacing.pkl

echo "Data augmentation complete for dataset SEGTHOR_CLEAN_AUG_ALB"
