#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=calc_metrics
#SBATCH --time=00:30:00
#SBATCH --output=./slurm_out/calc_metrics.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

source activate ai4mi

# Clone distorch
cd ~/
# git clone https://github.com/jeromerony/distorch.git
cd ~/distorch

pip install torch torchvision torchaudio

python -c "import torch; print(torch.cuda.is_available())"

pip install git+https://github.com/jeromerony/distorch.git

mkdir -p ~/ai4mi_project_group8/results/$MODEL_NAME/gt
for d in ~/ai4mi_project_group8/data/segthor_fixed/train/Patient_*; do
    id=$(basename "$d") 
    cp "$d/GT.nii.gz" ~/ai4mi_project_group8/results/$MODEL_NAME/gt/${id}.nii.gz
done

python compute_metrics.py \
  --ref_folder ~/ai4mi_project_group8/results/$MODEL_NAME/gt \
  --pred_folder ~/ai4mi_project_group8/results/$MODEL_NAME/stitched_pred \
  --ref_extension .nii.gz \
  --pred_extension .nii.gz \
  --num_classes 5 \
  --metrics 3d_dice 3d_hd95 3d_hd 3d_assd 3d_nsd 3d_jaccard \
  --save_folder ~/ai4mi_project_group8/results/$MODEL_NAME/metrics \
  --chill

