#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=compute_metrics
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=8GB
#SBATCH --time=00:10:00
#SBATCH --output=out/compute_metrics.log

module load 2023
module load Anaconda3/2023.07-2

cd $HOME/ai4mi_project_group8/
source $(conda info --base)/etc/profile.d/conda.sh
source activate ai4mi_env

pip install git+https://github.com/jeromerony/distorch.git

python compute_metrics.py \
  --ref_folder data/seghtor_predictions/gt \
  --pred_folder data/seghtor_predictions/pred \
  --ref_extension .nii.gz \
  --pred_extension .nii.gz \
  --num_classes 5 \
  --metrics 3d_dice 3d_hd95 3d_hd 3d_assd 3d_nsd 3d_jaccard confusion_matrix \
  --save_folder results/metrics_seghtor_val_pred \
  --overwrite


  # --ref_folder data/seghtor_predictions/gt \
  # --pred_folder data/seghtor_predictions/pred \