#!/bin/bash
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=InstallAI4MIEnvironmentData
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:30:00
#SBATCH --output=out/data_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Change to your project directory
cd $HOME/ai4mi_project_group8/

# Activate the conda environment
source activate ai4mi_env

make data/SEGTHOR
