#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=full_pipeline_parallel
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64GB
#SBATCH --time=03:00:00
#SBATCH --output=out/inference.log

module load 2023
module load Anaconda3/2023.07-2

cd $HOME/ai4mi_project_group8/
source $(conda info --base)/etc/profile.d/conda.sh
source activate ai4mi_env

export OMP_NUM_THREADS=2
export MKL_NUM_THREADS=2
export OPENBLAS_NUM_THREADS=2

python -O main.py   --dataset SEGTHOR_PREPROCESSED   --run_name test   --mode full   --epochs 75   \
    --dest results_test/   --gpu   --seed 3 --inference_pkl results/BEST_MODEL_DIR/bestmodel.pkl

python stitch.py \
  --data_folder results_test/test \
  --dest_folder results_test/stitched \
  --num_classes 5 \
  --grp_regex "(Patient_\\d\\d)_\\d\\d\\d\\d" \
  --source_scan_pattern "data/segthor_fixed/test/{id_}.nii.gz"