#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=create_data
#SBATCH --time=00:30:00
#SBATCH --output=./slurm_out/plot_perf.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

cd ~/ai4mi_project_group8

source activate ai4mi

mkdir results/$MODEL_NAME/plots

# Dice validation
python plot.py --metric_file results/$MODEL_NAME/dice_val.npy \
               --dest results/$MODEL_NAME/plots/dice_val.png --headless

# Dice training
python plot.py --metric_file results/$MODEL_NAME/dice_tra.npy \
               --dest results/$MODEL_NAME/plots/dice_train.png --headless

# Loss validation
python plot.py --metric_file results/$MODEL_NAME/loss_val.npy \
               --dest results/$MODEL_NAME/plots/loss_val.png --headless

# Loss training
python plot.py --metric_file results/$MODEL_NAME/loss_tra.npy \
               --dest results/$MODEL_NAME/plots/loss_train.png --headless

