#!/bin/bash
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=data
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:30:00
#SBATCH --output=out/slice_%A.out

module load 2023
module load Anaconda3/2023.07-2
source activate ai4mi_env

cd /home/scur1049/ai4mi_project_group8

python -O sabotage.py --mode inv --source_dir data/segthor_train --dest_dir data/segthor_fixed_tmp -K 2 --regex_gt "GT.nii.gz" -p 4

mv data/segthor_fixed_tmp data/segthor_fixed

python -O slice_segthor.py --source_dir data/segthor_fixed --dest_dir data/SEGTHOR_CLEAN \
        --shape 256 256 --retain 10 -p -1
