#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=stitch_prediction
#SBATCH --time=01:30:00
#SBATCH --output=./slurm_out/stitch_prediction.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

cd ~/ai4mi_project_group8

source activate ai4mi

echo "Running stitching for model: $MODEL_NAME"

python stitch.py \
  --data_folder results/$MODEL_NAME/best_epoch/val \
  --dest_folder results/$MODEL_NAME/stitched_pred \
  --num_classes 5 \
  --grp_regex "(Patient_\d\d)_\d\d\d\d" \
  --source_scan_pattern "data/segthor_train/train/{id_}/GT.nii.gz"

echo "Stitching complete for $MODEL_NAME"