#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=metrics
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64GB
#SBATCH --time=02:00:00
#SBATCH --output=out/metrics.log

module load 2023
module load Anaconda3/2023.07-2

# Change to your project directory
cd $HOME/ai4mi_project_group8/
source $(conda info --base)/etc/profile.d/conda.sh
source activate ai4mi_env


# Limit BLAS threads to reduce memory pressure
export OMP_NUM_THREADS=2
export MKL_NUM_THREADS=2
export OPENBLAS_NUM_THREADS=2

# Training
python -O main.py --dataset SEGTHOR_CLEAN --mode full --epoch 25 --dest "/home/scur1049/ai4mi_project_group8/results" --gpu