#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=train_model
#SBATCH --time=02:30:00
#SBATCH --output=./slurm_out/train_model.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

cd ~/ai4mi_project_group8

source activate ai4mi

pip install wandb

python -O main.py --dataset $DATA_NAME --mode full --epochs 25 --dest results/$MODEL_NAME --gpu

echo "Training complete for $MODEL_NAME on dataset $DATA_NAME"
